### ISSUE TITLE
File Ownership

### ISSUE THREAD

**Issue by HaileeCS** [GameServerManagers/LinuxGSM-Docs#31]
csgoserver@DM:~$ ./csgoserver restart
[ FAIL ] Stopping csgoserver: Permissions issues found
Information! The following directory does not have the correct permissions:
total 44
drwxrwxr-x 8 csgoserver csgoserver  4096 Oct  7 15:53 Steam
-rwxrwxr-x 1 csgoserver csgoserver 11834 Oct  7 15:31 csgoserver
drwxrwxr-x 7 csgoserver csgoserver  4096 Oct  7 15:32 lgsm
-rwxrwxr-x 1 csgoserver csgoserver 11828 Oct  7 15:31 linuxgsm.sh
drwxrwxr-x 4 csgoserver csgoserver  4096 Oct  7 15:32 log
drwxrwxr-x 6 csgoserver csgoserver  4096 Oct  7 16:21 serverfiles
drwxrwxr-x 7 csgoserver csgoserver  4096 Oct  7 15:32 steamcmd
I keep getting this error can someone help?

**Comment by dgibbs64** [comment]
Wrong repository
