### ISSUE TITLE
Problem with config - always overwrite by default 

### ISSUE THREAD

**Issue by 81n90** [GameServerManagers/LinuxGSM-Docs#45]
When I start new server (rustserver), config /lgsm/config-lgsm/rustserver/common.cfg - rustserver not use this file. Just server.cfg from /lgsm/config-default/config-game/server.cfg

**Comment by 81n90** [comment]
I temporary fixed this by editing file /cfg/server.cfg - readonly and lgsm can't rewrite this normal config.

**Comment by 81n90** [comment]
Why so difficult, not friendly config system in lgsm?

**Comment by dgibbs64** [comment]
Wrong repository
