### ISSUE TITLE
Links are the same color as normal text

### ISSUE THREAD

**Issue by GregariousJB** [GameServerManagers/LinuxGSM-Docs#68]
If you _really_ don't want links to have an underline, fine, but for the love of god, make sure they're a different color from the normal text around them.

**Comment by dgibbs64** [comment]
speak with GitBook

**Comment by GregariousJB** [comment]
> speak with GitBook

[They told me their links are colored differently than the normal text](https://gitbookio.gitbooks.io/documentation/content/index.html).

They also told me you might find [CSS styling in the styles/website.css](https://gitbookio.gitbooks.io/documentation/content/styling/book.html) file.
