### ISSUE TITLE
Documentation doesn't mention how to install specific version of Minecraft: Java Edition version.

### ISSUE THREAD

**Issue by AlperShal** [GameServerManagers/LinuxGSM-Docs#83]
https://docs.linuxgsm.com/game-servers/minecraft
If you click to link, you can see that it only says: `With LinuxGSM you can specify a specific release/snapshot or the latest release/snapshot. By default, LinuxGSM will use the latest release.`
But it doesn't say how. So, I would like instructions to be added.

**Comment by Claiyc** [comment]
Documentation may be updated there, however you can easily find out by looking into the _default.cfg (which contains documentation as well): https://github.com/GameServerManagers/LinuxGSM/blob/21277aa827a45478d57eed6b1790966d59bc4eed/lgsm/config-default/config-lgsm/mcserver/_default.cfg#L19

**Comment by AlperShal** [comment]
Ooooh, I see. I checked that "_default.cfg" file in my Minecraft game server installation yesterday but it was just empty. After I have checked that link you sent I reinstalled my game server and now it is as it should be. Sorry for taking your time.
